In [1]:
#rename可以用，可以用loc来修改数据，或查找符合条件的数据
#between和isin选择满足条件的行
#& and | 且和或

In [6]:
import pandas as pd
import numpy as np
import os
os.getcwd()
os.chdir(r'/Users/wangxiang/Desktop/')

In [8]:
df1 = pd.read_excel('Student_Information.xls')

In [9]:
df1.head(5)#dataframe 格式

   年级      班级         姓名   入学年        学号 性别
0  高三  高17级1班     阮琦Rita  2016  16110276  女
1  高三  高17级1班   郭悦淇Linda  2016  16110230  女
2  高三  高17级1班  王一尘Robert  2016  16110200  男
3  高三  高17级1班    潘柏羽Panl  2017  16110156  男
4  高三  高17级1班   马一菲Alisa  2017  16110251  女

In [11]:
df1.loc[df1['入学年']==2016,'入学年']=1111 #修改了column，不加后面的可以单纯筛选

In [12]:
df1.head(5)

   年级      班级         姓名   入学年        学号 性别
0  高三  高17级1班     阮琦Rita  1111  16110276  女
1  高三  高17级1班   郭悦淇Linda  1111  16110230  女
2  高三  高17级1班  王一尘Robert  1111  16110200  男
3  高三  高17级1班    潘柏羽Panl  2017  16110156  男
4  高三  高17级1班   马一菲Alisa  2017  16110251  女

In [13]:
df1.rename(columns={'年级':'grade','姓名':'name','班级':'class','性别':'gender'})#只是看看效果

     grade   class               name   入学年        学号 gender
0       高三  高17级1班             阮琦Rita  1111  16110276      女
1       高三  高17级1班           郭悦淇Linda  1111  16110230      女
2       高三  高17级1班          王一尘Robert  1111  16110200      男
3       高三  高17级1班            潘柏羽Panl  2017  16110156      男
4       高三  高17级1班           马一菲Alisa  2017  16110251      女
5       高三  高17级1班            王茗艳Mary  1111  16110223      女
6       高三  高17级1班            杨小佳Gina  1111  16110157      女
7       高三  高17级1班           徐梁轩Allen  1111  16110193      男
8       高三  高17级1班           胡骏龙Peter  1111  16110135      男
9       高三  高17级1班         崔子杰Charlie  2017  16110272      男
10      高三  高17级1班             潘孟骐Sam  2017  16110165      男
11      高三  高17级1班            惠俊皓Tony  1111  16110154      男
12      高三  高17级1班     丁羽晨 Dylan Ding  1111  16110116      男
13      高三  高17级1班           梁言Rachel  1111  16110147      女
14      高三  高17级1班            李欣艺Iris  1111  16110207      女
15      高三  高17级1班         江雪鲲 Arnold  1111  16110149      男
16      高三  高17级1班          任之杰 Tiger  1111  16110220      男
17      高三  高17级1班            薛博鸿Bill  1111  16110181      男
18      高三  高17级1班           唐一鸣Ethel  2017  16110282      女
19      高三  高17级1班          吴弼潭Victor  1111  16110275      男
20      高三  高17级1班          陈雪阳Sharon  2017  16110283      女
21      高三  高17级1班           金子越Felix  2017  16110136      男
22      高三  高17级1班          王遥 Angela  2017  16110141      女
23      高三  高17级1班             于道阳Rex  2017  16110203      男
24      高三  高17级1班          邓铭章Damien  2017  16110124      男
25      高三  高17级2班            李自航Mike  1111  16110173      男
26      高三  高17级2班           杨知新shine  1111  16110219      男
27      高三  高17级2班            徐薇娜Mina  1111  16110184      女
28      高三  高17级2班             刘正源Ray  2018  16110479      男
29      高三  高17级2班            段维真Judt  2017  16110182      女
..     ...     ...                ...   ...       ...    ...
529  四年制高一  高18级1班           赵欣然-Jill  1111  16070126      女
530  四年制高一  高18级1班            杨景森-Sam  1111  16070224      男
531  四年制高一  高18级1班          张泽曦-Jason  1111  16070184      男
532  四年制高一  高18级1班           洪亮-Jerry  1111  16070260      男
533  四年制高一  高18级1班          刘家萁-Cindy  1111  16070137      女
534  四年制高一  高18级1班            王珏-Rich  1111  16070162      男
535  四年制高一  高18级1班          刘瀚文-Chris  1111  16070233      男
536  四年制高一  高18级1班       贾墨川-Alex Jia  1111  16070150      男
537  四年制高一  高18级1班         邢瑞祺-Rachel  1111  16070267      女
538  四年制高一  高18级2班           张雅涵Cathy  2018  18110257      女
539  四年制高一  高18级2班            朱淼Wendy  2018  18110247      女
540  四年制高一  高18级2班         高元熙  Angel  2018  18110243      女
541  四年制高一  高18级2班          董泽宇Gluten  2018  18110256      男
542  四年制高一  高18级2班         程兆煜Charlie  2018  18110259      男
543  四年制高一  高18级2班  张简之Jiangzhi Zhang  2018  18110246      男
544  四年制高一  高18级2班            蒋京涛Evan  2018  18110242      男
545  四年制高一  高18级2班          唐恺辰 Kevin  2018  18110258      男
546  四年制高一  高18级2班          赵毓子Spring  2018  18110261      女
547  四年制高一  高18级2班           王恺Steven  2018  18110250      男
548  四年制高一  高18级2班            孙雨涵Anna  2018  18110249      女
549  四年制高一  高18级2班         王嘉琪Allison  2018  18110244      女
550  四年制高一  高18级2班           于艺童Jenny  2018  18110248      女
551  四年制高一  高18级2班             董泓坤Jim  2018  18110262      男
552  四年制高一  高18级2班           姜紫珩Jacob  2018  18110252      男
553  四年制高一  高18级2班           方晗语Milly  2018  18110245      女
554  四年制高一  高18级2班         汤懿萱Tiffany  2018  18110251      女
555  四年制高一  高18级2班           耿嘉悦Susan  2018  18110253      女
556  四年制高一  高18级2班           戴乐萱Linda  2018  18110254      女
557  四年制高一  高18级2班          陈希林 Bruce  2018  18110260      男
558  四年制高一  高18级2班             陈天烨Eli  2018  18110255      男

[559 rows x 6 columns]

In [14]:
df1.rename(columns={'年级':'grade','姓名':'name','班级':'class','性别':'gender'},inplace=True)#来真的

In [16]:
df1.head(5)

  grade   class       name   入学年        学号 gender
0    高三  高17级1班     阮琦Rita  1111  16110276      女
1    高三  高17级1班   郭悦淇Linda  1111  16110230      女
2    高三  高17级1班  王一尘Robert  1111  16110200      男
3    高三  高17级1班    潘柏羽Panl  2017  16110156      男
4    高三  高17级1班   马一菲Alisa  2017  16110251      女

In [21]:
df1.rename(index={3:3.14},inplace=True)#change rows, 话说就加inplace啦

In [22]:
df1.iloc[:5]#与标签无关，比如3.14hh，按照位置来的

     grade   class       name   入学年        学号 gender
0.00    高三  高17级1班     阮琦Rita  1111  16110276      女
1.00    高三  高17级1班   郭悦淇Linda  1111  16110230      女
2.00    高三  高17级1班  王一尘Robert  1111  16110200      男
3.14    高三  高17级1班    潘柏羽Panl  2017  16110156      男
4.00    高三  高17级1班   马一菲Alisa  2017  16110251      女

In [23]:
df1.loc[:5]

     grade   class       name   入学年        学号 gender
0.00    高三  高17级1班     阮琦Rita  1111  16110276      女
1.00    高三  高17级1班   郭悦淇Linda  1111  16110230      女
2.00    高三  高17级1班  王一尘Robert  1111  16110200      男
3.14    高三  高17级1班    潘柏羽Panl  2017  16110156      男
4.00    高三  高17级1班   马一菲Alisa  2017  16110251      女
5.00    高三  高17级1班    王茗艳Mary  1111  16110223      女

In [24]:
df1.reset_index(drop=True,inplace=True)#重置成功咯

In [25]:
df1

     grade   class               name   入学年        学号 gender
0       高三  高17级1班             阮琦Rita  1111  16110276      女
1       高三  高17级1班           郭悦淇Linda  1111  16110230      女
2       高三  高17级1班          王一尘Robert  1111  16110200      男
3       高三  高17级1班            潘柏羽Panl  2017  16110156      男
4       高三  高17级1班           马一菲Alisa  2017  16110251      女
5       高三  高17级1班            王茗艳Mary  1111  16110223      女
6       高三  高17级1班            杨小佳Gina  1111  16110157      女
7       高三  高17级1班           徐梁轩Allen  1111  16110193      男
8       高三  高17级1班           胡骏龙Peter  1111  16110135      男
9       高三  高17级1班         崔子杰Charlie  2017  16110272      男
10      高三  高17级1班             潘孟骐Sam  2017  16110165      男
11      高三  高17级1班            惠俊皓Tony  1111  16110154      男
12      高三  高17级1班     丁羽晨 Dylan Ding  1111  16110116      男
13      高三  高17级1班           梁言Rachel  1111  16110147      女
14      高三  高17级1班            李欣艺Iris  1111  16110207      女
15      高三  高17级1班         江雪鲲 Arnold  1111  16110149      男
16      高三  高17级1班          任之杰 Tiger  1111  16110220      男
17      高三  高17级1班            薛博鸿Bill  1111  16110181      男
18      高三  高17级1班           唐一鸣Ethel  2017  16110282      女
19      高三  高17级1班          吴弼潭Victor  1111  16110275      男
20      高三  高17级1班          陈雪阳Sharon  2017  16110283      女
21      高三  高17级1班           金子越Felix  2017  16110136      男
22      高三  高17级1班          王遥 Angela  2017  16110141      女
23      高三  高17级1班             于道阳Rex  2017  16110203      男
24      高三  高17级1班          邓铭章Damien  2017  16110124      男
25      高三  高17级2班            李自航Mike  1111  16110173      男
26      高三  高17级2班           杨知新shine  1111  16110219      男
27      高三  高17级2班            徐薇娜Mina  1111  16110184      女
28      高三  高17级2班             刘正源Ray  2018  16110479      男
29      高三  高17级2班            段维真Judt  2017  16110182      女
..     ...     ...                ...   ...       ...    ...
529  四年制高一  高18级1班           赵欣然-Jill  1111  16070126      女
530  四年制高一  高18级1班            杨景森-Sam  1111  16070224      男
531  四年制高一  高18级1班          张泽曦-Jason  1111  16070184      男
532  四年制高一  高18级1班           洪亮-Jerry  1111  16070260      男
533  四年制高一  高18级1班          刘家萁-Cindy  1111  16070137      女
534  四年制高一  高18级1班            王珏-Rich  1111  16070162      男
535  四年制高一  高18级1班          刘瀚文-Chris  1111  16070233      男
536  四年制高一  高18级1班       贾墨川-Alex Jia  1111  16070150      男
537  四年制高一  高18级1班         邢瑞祺-Rachel  1111  16070267      女
538  四年制高一  高18级2班           张雅涵Cathy  2018  18110257      女
539  四年制高一  高18级2班            朱淼Wendy  2018  18110247      女
540  四年制高一  高18级2班         高元熙  Angel  2018  18110243      女
541  四年制高一  高18级2班          董泽宇Gluten  2018  18110256      男
542  四年制高一  高18级2班         程兆煜Charlie  2018  18110259      男
543  四年制高一  高18级2班  张简之Jiangzhi Zhang  2018  18110246      男
544  四年制高一  高18级2班            蒋京涛Evan  2018  18110242      男
545  四年制高一  高18级2班          唐恺辰 Kevin  2018  18110258      男
546  四年制高一  高18级2班          赵毓子Spring  2018  18110261      女
547  四年制高一  高18级2班           王恺Steven  2018  18110250      男
548  四年制高一  高18级2班            孙雨涵Anna  2018  18110249      女
549  四年制高一  高18级2班         王嘉琪Allison  2018  18110244      女
550  四年制高一  高18级2班           于艺童Jenny  2018  18110248      女
551  四年制高一  高18级2班             董泓坤Jim  2018  18110262      男
552  四年制高一  高18级2班           姜紫珩Jacob  2018  18110252      男
553  四年制高一  高18级2班           方晗语Milly  2018  18110245      女
554  四年制高一  高18级2班         汤懿萱Tiffany  2018  18110251      女
555  四年制高一  高18级2班           耿嘉悦Susan  2018  18110253      女
556  四年制高一  高18级2班           戴乐萱Linda  2018  18110254      女
557  四年制高一  高18级2班          陈希林 Bruce  2018  18110260      男
558  四年制高一  高18级2班             陈天烨Eli  2018  18110255      男

[559 rows x 6 columns]

In [29]:
df1.head(2)

  grade   class      name   入学年        学号 gender
0    高三  高17级1班    阮琦Rita  1111  16110276      女
1    高三  高17级1班  郭悦淇Linda  1111  16110230      女

In [31]:
df1['入学年']>1111

0      False
1      False
2      False
3       True
4       True
5      False
6      False
7      False
8      False
9       True
10      True
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18      True
19     False
20      True
21      True
22      True
23      True
24      True
25     False
26     False
27     False
28      True
29      True
       ...
529    False
530    False
531    False
532    False
533    False
534    False
535    False
536    False
537    False
538     True
539     True
540     True
541     True
542     True
543     True
544     True
545     True
546     True
547     True
548     True
549     True
550     True
551     True
552     True
553     True
554     True
555     True
556     True
557     True
558     True
Name: 入学年, Length: 559, dtype: bool

In [33]:
df1[df1['入学年']>1111]#现在就可以筛选咯

     grade    class               name   入学年        学号 gender
3       高三   高17级1班            潘柏羽Panl  2017  16110156      男
4       高三   高17级1班           马一菲Alisa  2017  16110251      女
9       高三   高17级1班         崔子杰Charlie  2017  16110272      男
10      高三   高17级1班             潘孟骐Sam  2017  16110165      男
18      高三   高17级1班           唐一鸣Ethel  2017  16110282      女
20      高三   高17级1班          陈雪阳Sharon  2017  16110283      女
21      高三   高17级1班           金子越Felix  2017  16110136      男
22      高三   高17级1班          王遥 Angela  2017  16110141      女
23      高三   高17级1班             于道阳Rex  2017  16110203      男
24      高三   高17级1班          邓铭章Damien  2017  16110124      男
28      高三   高17级2班             刘正源Ray  2018  16110479      男
29      高三   高17级2班            段维真Judt  2017  16110182      女
30      高三   高17级2班            黄子昂Tony  2017  16110255      男
33      高三   高17级2班            丛子祺Zach  2018  16110478      男
41      高三   高17级2班           李奕葳Clare  2017  16110120      女
42      高三   高17级2班          贾沛旺Justin  2017  16110215      男
53      高三   高17级3班           孙梦阳Sissi  2017  16110236      女
55      高三   高17级3班            魏潇然Joey  2017  16110476      男
61      高三   高17级3班          张学才Steven  2017  16110121      男
65      高三   高17级3班           赵晓闻Wendy  2017  16110222      女
70      高三   高17级4班          刘笑盈regina  2017  16110210      女
72      高三   高17级4班             陈曦Tina  2017  16110191      女
74      高三   高17级4班           孟琳琳Sarah  2017  16110202      女
76      高三   高17级4班           宁云昊Jimmy  2017  16110273      男
79      高三   高17级4班           曹文博Kevin  2017  16110174      男
89      高三   高17级5班          胡天艺Vivian  2017  16110257      女
91      高三   高17级5班           梁凯寒Liang  2017  16110284      男
94      高三   高17级5班                李丝璇  2017  16110274      女
97      高三   高17级5班             赵凯John  2017  16110123      男
98      高三   高17级5班        张一博Tom Dill  2017  16110267      男
..     ...      ...                ...   ...       ...    ...
508  四年制高二  四高18级2班         王彤羽Crystal  2017  17150124      女
509  四年制高二  四高18级2班             高启翔Jim  2017  17150120      男
510  四年制高二  四高18级2班           雷佳楠Nancy  2017  17150276      女
511  四年制高二  四高18级2班     魏暄雯Jessica Wei  2017  17150117      女
512  四年制高二  四高18级2班            王米拉Mila  2017  17150102      女
513  四年制高二  四高18级2班            胡诗琪Gina  2017  17150108      女
514  四年制高二  四高18级2班   张嘉颐Jessica Zhang  2017  17150273      女
515  四年制高一  四高18级2班            杨拉卡Luke  2018  17150103      男
517  四年制高一   高18级1班          陈哲远-Jonas  2017  16070249      男
538  四年制高一   高18级2班           张雅涵Cathy  2018  18110257      女
539  四年制高一   高18级2班            朱淼Wendy  2018  18110247      女
540  四年制高一   高18级2班         高元熙  Angel  2018  18110243      女
541  四年制高一   高18级2班          董泽宇Gluten  2018  18110256      男
542  四年制高一   高18级2班         程兆煜Charlie  2018  18110259      男
543  四年制高一   高18级2班  张简之Jiangzhi Zhang  2018  18110246      男
544  四年制高一   高18级2班            蒋京涛Evan  2018  18110242      男
545  四年制高一   高18级2班          唐恺辰 Kevin  2018  18110258      男
546  四年制高一   高18级2班          赵毓子Spring  2018  18110261      女
547  四年制高一   高18级2班           王恺Steven  2018  18110250      男
548  四年制高一   高18级2班            孙雨涵Anna  2018  18110249      女
549  四年制高一   高18级2班         王嘉琪Allison  2018  18110244      女
550  四年制高一   高18级2班           于艺童Jenny  2018  18110248      女
551  四年制高一   高18级2班             董泓坤Jim  2018  18110262      男
552  四年制高一   高18级2班           姜紫珩Jacob  2018  18110252      男
553  四年制高一   高18级2班           方晗语Milly  2018  18110245      女
554  四年制高一   高18级2班         汤懿萱Tiffany  2018  18110251      女
555  四年制高一   高18级2班           耿嘉悦Susan  2018  18110253      女
556  四年制高一   高18级2班           戴乐萱Linda  2018  18110254      女
557  四年制高一   高18级2班          陈希林 Bruce  2018  18110260      男
558  四年制高一   高18级2班             陈天烨Eli  2018  18110255      男

[404 rows x 6 columns]

In [37]:
df1[(df1['入学年']>1111)& (df1['入学年']<2018)]#现在就可以筛选咯

     grade    class              name   入学年        学号 gender
3       高三   高17级1班           潘柏羽Panl  2017  16110156      男
4       高三   高17级1班          马一菲Alisa  2017  16110251      女
9       高三   高17级1班        崔子杰Charlie  2017  16110272      男
10      高三   高17级1班            潘孟骐Sam  2017  16110165      男
18      高三   高17级1班          唐一鸣Ethel  2017  16110282      女
20      高三   高17级1班         陈雪阳Sharon  2017  16110283      女
21      高三   高17级1班          金子越Felix  2017  16110136      男
22      高三   高17级1班         王遥 Angela  2017  16110141      女
23      高三   高17级1班            于道阳Rex  2017  16110203      男
24      高三   高17级1班         邓铭章Damien  2017  16110124      男
29      高三   高17级2班           段维真Judt  2017  16110182      女
30      高三   高17级2班           黄子昂Tony  2017  16110255      男
41      高三   高17级2班          李奕葳Clare  2017  16110120      女
42      高三   高17级2班         贾沛旺Justin  2017  16110215      男
53      高三   高17级3班          孙梦阳Sissi  2017  16110236      女
55      高三   高17级3班           魏潇然Joey  2017  16110476      男
61      高三   高17级3班         张学才Steven  2017  16110121      男
65      高三   高17级3班          赵晓闻Wendy  2017  16110222      女
70      高三   高17级4班         刘笑盈regina  2017  16110210      女
72      高三   高17级4班            陈曦Tina  2017  16110191      女
74      高三   高17级4班          孟琳琳Sarah  2017  16110202      女
76      高三   高17级4班          宁云昊Jimmy  2017  16110273      男
79      高三   高17级4班          曹文博Kevin  2017  16110174      男
89      高三   高17级5班         胡天艺Vivian  2017  16110257      女
91      高三   高17级5班          梁凯寒Liang  2017  16110284      男
94      高三   高17级5班               李丝璇  2017  16110274      女
97      高三   高17级5班            赵凯John  2017  16110123      男
98      高三   高17级5班       张一博Tom Dill  2017  16110267      男
103     高三   高17级5班        李泽亮Charles  2017  16110245      男
113     高三   高17级6班          张赵跃Steve  2017  16110242      男
..     ...      ...               ...   ...       ...    ...
484  四年制高二  四高18级1班          文一凡Danny  2017  17150121      男
485  四年制高二  四高18级1班      郄茹茵 Isabella  2017  17150115      女
486  四年制高二  四高18级1班            郭雁南Amy  2017  17150127      女
487  四年制高二  四高18级1班          张灵竹Grace  2017  17150268      女
488  四年制高二  四高18级1班          李嘉淇Frank  2017  17150275      男
489  四年制高二  四高18级1班           任世钰Ivan  2017  17150274      男
491  四年制高二  四高18级1班          程雨歆Kevin  2017  17150118      男
492  四年制高二  四高18级1班        韩露仪Cynthia  2017  17150279      女
493  四年制高二  四高18级1班          陈志澎Bambi  2017  17150277      男
494  四年制高二  四高18级1班           卢茶燕Lucy  2017  17150267      女
495  四年制高二  四高18级1班           王嘉玺Tony  2017  17150278      男
497  四年制高二  四高18级1班           吴梓涵Eric  2017  17150123      男
498  四年制高二  四高18级1班       刘宇珏Virginia  2017  17150270      女
499  四年制高二  四高18级2班        陈俊杰William  2017  17150110      男
500  四年制高二  四高18级2班          周恺轶Tracy  2017  17150269      女
501  四年制高二  四高18级2班         奥欣谕Olivia  2017  17150119      女
502  四年制高二  四高18级2班           许民杰Jack  2017  17150111      男
503  四年制高二  四高18级2班           倪梓恬Tina  2017  17150125      女
504  四年制高二  四高18级2班         徐司城Steven  2017  17150126      男
505  四年制高二  四高18级2班          侯博韬Harry  2017  17150114      男
506  四年制高二  四高18级2班         任天一Derick  2017  17150116      男
507  四年制高二  四高18级2班         刘斯庸Cellia  2017  17150112      女
508  四年制高二  四高18级2班        王彤羽Crystal  2017  17150124      女
509  四年制高二  四高18级2班            高启翔Jim  2017  17150120      男
510  四年制高二  四高18级2班          雷佳楠Nancy  2017  17150276      女
511  四年制高二  四高18级2班    魏暄雯Jessica Wei  2017  17150117      女
512  四年制高二  四高18级2班           王米拉Mila  2017  17150102      女
513  四年制高二  四高18级2班           胡诗琪Gina  2017  17150108      女
514  四年制高二  四高18级2班  张嘉颐Jessica Zhang  2017  17150273      女
517  四年制高一   高18级1班         陈哲远-Jonas  2017  16070249      男

[78 rows x 6 columns]

In [39]:
df1['入学年'].between(4,10,inclusive=True)

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...
529    False
530    False
531    False
532    False
533    False
534    False
535    False
536    False
537    False
538    False
539    False
540    False
541    False
542    False
543    False
544    False
545    False
546    False
547    False
548    False
549    False
550    False
551    False
552    False
553    False
554    False
555    False
556    False
557    False
558    False
Name: 入学年, Length: 559, dtype: bool

In [40]:
df1[df1['入学年'].between(4,10,inclusive=True)]

Empty DataFrame
Columns: [grade, class, name, 入学年, 学号, gender]
Index: []

In [42]:
df1['入学年'].isin([1111,1110,2017])#同时筛选多个

0       True
1       True
2       True
3       True
4       True
5       True
6       True
7       True
8       True
9       True
10      True
11      True
12      True
13      True
14      True
15      True
16      True
17      True
18      True
19      True
20      True
21      True
22      True
23      True
24      True
25      True
26      True
27      True
28     False
29      True
       ...
529     True
530     True
531     True
532     True
533     True
534     True
535     True
536     True
537     True
538    False
539    False
540    False
541    False
542    False
543    False
544    False
545    False
546    False
547    False
548    False
549    False
550    False
551    False
552    False
553    False
554    False
555    False
556    False
557    False
558    False
Name: 入学年, Length: 559, dtype: bool

In [44]:
df1[df1['入学年'].isin([1111,1110,2017])].head(10)

  grade   class        name   入学年        学号 gender
0    高三  高17级1班      阮琦Rita  1111  16110276      女
1    高三  高17级1班    郭悦淇Linda  1111  16110230      女
2    高三  高17级1班   王一尘Robert  1111  16110200      男
3    高三  高17级1班     潘柏羽Panl  2017  16110156      男
4    高三  高17级1班    马一菲Alisa  2017  16110251      女
5    高三  高17级1班     王茗艳Mary  1111  16110223      女
6    高三  高17级1班     杨小佳Gina  1111  16110157      女
7    高三  高17级1班    徐梁轩Allen  1111  16110193      男
8    高三  高17级1班    胡骏龙Peter  1111  16110135      男
9    高三  高17级1班  崔子杰Charlie  2017  16110272      男